# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b28aacf5413b60104dbb82fa463cd9173f6a4f745f8360c5e0acc352f4400fa79a1f2e7ee48263aa52d6144dec43cb951512c9084a4f218628424fc5d2563b5

test:
  secret_key_base: 225a69401c6e3d72c7d4f76a0ef565fc11d79469f30c264f50e7f6f3e49fea93bf9ba7de6786be778478b2ad1a67102bc16c67a4c53bc7fd85b4968770fba488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
